In [4]:
# =========================
# NIFTY 50 Symbols
# =========================
nifty_50_symbols = [
    "ADANIENT","ADANIPORTS","APOLLOHOSP","ASIANPAINT","AXISBANK",
    "BAJAJ-AUTO","BAJFINANCE","BAJAJFINSV","BPCL","BHARTIARTL",
    "BRITANNIA","CIPLA","COALINDIA","DIVISLAB","DRREDDY",
    "EICHERMOT","GRASIM","HCLTECH","HDFCBANK","HDFCLIFE",
    "HEROMOTOCO","HINDALCO","HINDUNILVR","ICICIBANK","ITC",
    "INDUSINDBK","INFY","JSWSTEEL","KOTAKBANK","LT",
    "M&M","MARUTI","NESTLEIND","NTPC","ONGC",
    "POWERGRID","RELIANCE","SBILIFE","SBIN","SUNPHARMA",
    "TCS","TATACONSUM","TATAMOTORS","TATASTEEL","TECHM",
    "TITAN","ULTRACEMCO","UPL","WIPRO","LTM"
]

In [5]:
len(nifty_50_symbols)

50

In [3]:
import streamlit as st
import pandas as pd
import math
import yfinance as yf
import plotly.graph_objects as go
import utils.helpers_functions as hf

from datetime import date, timedelta
from config import Settings
from markets.us import Us_Market
from markets.india import India_Market

In [4]:
settings = Settings()



choice = 'US'
market, stock_df, group_size = hf.get_market(choice)

# =========================
# Group Selector
# =========================


total_groups = hf.total_groups(stock_df,group_size)


group_no = 1


df_group = hf.get_group(group_no,group_size,stock_df)

# Create label dict for plot
label_column = hf.MARKET_LABEL_COLUMNS.get(choice, 'SYMBOL')
label_dict = dict(zip(df_group['SYMBOL'], df_group[label_column])) if label_column in df_group.columns else {s: s for s in df_group['SYMBOL']}



symbols = market.get_symbols(df_group)
start_date = '2026-01-01'
end_date = '2026-04-04'
price_df = hf.get_data(symbols,start_date,end_date)

if price_df.empty:
    st.warning("No price data available.")
    st.stop()

# =========================
# Returns Calculation
# =========================
total_pct_df = hf.calculate_returs(price_df)

2026-04-25 11:20:10.817 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-25 11:20:10.822 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-25 11:20:10.825 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-25 11:20:10.845 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-25 11:20:10.850 WARNING streamlit.runtime.state.session_state_proxy: Session state does not function when running a script without `streamlit run`
2026-04-25 11:20:10.856 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-25 11:20:11.672
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run d:\PROJECTS\stock_performance_dashboard\.venv\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]
2026-04-25 11:20:11.673 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-25 11:20:11.673 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [5]:
price_df

Ticker,AAPL,ABBV,AMAT,AMD,AMGN,AMZN,AVGO,AXP,BAC,CAT,...,PM,RTX,TMUS,TSLA,UNH,V,VZ,WFC,WMT,XOM
Date,,,,,,,,,,,,,,,,,,,,,
2026-01-02,270.756653,225.608078,268.535095,223.470001,325.385376,226.500000,346.892303,371.555389,55.635487,595.878662,...,158.881683,186.630127,198.624939,438.070007,333.804901,345.766998,39.238792,94.734390,112.529060,121.837906
2026-01-05,267.010162,216.625458,283.965851,221.080002,318.512970,233.059998,342.701141,378.603088,56.570198,613.493896,...,158.445572,187.636765,199.898819,451.670013,339.381531,353.071930,38.957966,95.908623,112.479164,124.529961
2026-01-06,262.114716,220.314926,295.641296,214.350006,327.897949,240.929993,343.050385,382.351227,56.928177,620.454346,...,153.787155,189.769684,197.649628,432.959991,346.277924,356.824188,39.025749,95.918571,114.105820,120.248505
2026-01-07,260.086609,229.651733,291.836029,210.020004,339.289032,241.559998,342.780945,377.028076,55.327225,593.996765,...,153.777237,185.115143,196.345886,431.410004,339.064026,355.147644,38.861130,93.828850,112.489143,117.705444
2026-01-08,258.797852,220.511703,281.289185,204.679993,327.838348,246.289993,331.784027,381.773071,55.864193,605.557617,...,157.404861,186.550385,196.962936,435.799988,344.174286,351.505188,39.287216,95.132439,112.838425,122.096184
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-03-27,248.800003,207.677078,337.170013,201.990005,348.769989,199.339996,300.679993,291.348938,46.970001,694.078613,...,163.539993,189.710007,210.820007,361.829987,259.019989,295.519989,49.564514,77.190002,122.889999,170.990005
2026-03-30,246.630005,211.366470,323.119995,196.039993,349.000000,200.949997,293.410004,296.552490,47.230000,666.161743,...,164.830002,187.149994,213.940002,355.279999,261.790009,299.540009,49.554661,76.800003,123.500000,171.470001
2026-03-31,253.789993,215.700516,341.790009,203.429993,351.850006,208.270004,309.510010,301.526764,48.750000,707.113831,...,165.339996,192.899994,210.029999,371.750000,270.589996,302.239990,49.456142,79.610001,124.279999,169.660004
2026-04-01,255.630005,213.211166,353.799988,210.210007,353.279999,210.570007,313.489990,300.500031,49.270000,728.932251,...,157.330002,194.720001,204.250000,381.260010,273.980011,298.510010,48.658142,80.570000,124.739998,160.779999
2026-04-02,255.919998,207.121689,348.470001,217.500000,347.940002,209.770004,314.549988,300.179993,49.380001,715.857117,...,158.100006,196.210007,201.399994,360.589996,277.260010,300.799988,48.667999,80.599998,125.790001,160.690002

In [8]:
total_pct_df.to_clipboard()

In [ ]:
def calculate_pct_rank_delta(df,n_days):
    stock_cols = df.columns.drop(["mean_pct_chg", "median_pct_change", "std", "2std"], errors='ignore')

    
    pct_rank = df[stock_cols].rank(axis=1, pct=True) * 100
    n_days_ago = pct_rank.shift(n_days).iloc[-1].astype(int)
    current_day = pct_rank.iloc[-1].astype(int)
    current_day.rename("current_day_rank",inplace=True)
    n_days_ago.rename("n_days_ago_rank",inplace=True)
    delta_df = pd.merge(current_day,n_days_ago,left_index=True,right_index=True,how='inner')
    delta_df['rank_delta'] = delta_df['current_day_rank'] - delta_df['n_days_ago_rank']
    delta_df.sort_values(by='rank_delta',ascending=False,inplace = True)
    
    return delta_df

In [57]:
calculate_pct_rank_delta(total_pct_df,10)

        current_day_rank  n_days_ago_rank  rank_delta
Ticker
GS                    50               28          22
AMD                   52               34          18
BAC                   28               12          16
NFLX                  68               54          14
AAPL                  48               36          12
MS                    34               24          10
GEV                  100               92           8
WMT                   74               66           8
COST                  86               78           8
ABBV                  36               30           6
INTC                  92               86           6
JPM                   32               26           6
WFC                   12                6           6
MRK                   76               72           4
MCD                   60               56           4
AXP                    6                2           4
CAT                   88               84           4
XOM                   98               94           4
VZ                    90               88           2
LLY                   16               14           2
CSCO                  62               62           0
NVDA                  46               46           0
UNH                   10               10           0
V                     18               18           0
LIN                   80               80           0
JNJ                   82               82           0
ORCL                   2                4          -2
IBM                   14               16          -2
MA                    20               22          -2
CVX                   94               96          -2
AMZN                  38               40          -2
AMGN                  66               68          -2
AMAT                  96               98          -2
PG                    57               60          -3
PM                    54               57          -3
MSFT                   4                8          -4
KO                    72               76          -4
PEP                   70               74          -4
RTX                   64               70          -6
HD                    42               48          -6
LRCX                  84               90          -6
AVGO                  30               38          -8
GOOGL                 44               52          -8
TMUS                  56               64          -8
GOOG                  40               50         -10
GE                    22               32         -10
TSLA                   8               20         -12
PLTR                  26               42         -16
META                  24               44         -20
MU                    78              100         -22

In [9]:
round((pct_rank - pct_rank.shift(10)),2).iloc[-1].sort_values(ascending=False)

Ticker
GS       0.22
AMD      0.18
BAC      0.16
NFLX     0.14
AAPL     0.12
MS       0.10
GEV      0.08
WMT      0.08
COST     0.08
ABBV     0.06
INTC     0.06
JPM      0.06
WFC      0.06
MRK      0.04
MCD      0.04
AXP      0.04
CAT      0.04
XOM      0.04
VZ       0.02
LLY      0.02
CSCO     0.00
NVDA     0.00
UNH      0.00
V        0.00
LIN      0.00
JNJ      0.00
PG      -0.02
ORCL    -0.02
MA      -0.02
IBM     -0.02
AMZN    -0.02
AMGN    -0.02
AMAT    -0.02
CVX     -0.02
KO      -0.04
MSFT    -0.04
PM      -0.04
PEP     -0.04
RTX     -0.06
HD      -0.06
LRCX    -0.06
AVGO    -0.08
GOOGL   -0.08
TMUS    -0.08
GOOG    -0.10
GE      -0.10
TSLA    -0.12
PLTR    -0.16
META    -0.20
MU      -0.22
Name: 2026-04-02 00:00:00, dtype: float64